### ISSUE TITLE
Documentação e Treinamentos

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#397]
### Contexto do épico
Este épico tem o intuito de demandar atividades referente a documentações e treinamentos necessários ao desenvolvimento do Projeto Mapa da Saúde.

### Escopo
- [ ] **Revisão e organização de documentação**
- [ ] **Adaptação do material de documentação da Secult**
- [ ] **Elaboração de Cronograma de Treinamentos**
- [ ] **Organizar divisão de atividades entre Hacklab/ESP/Secult**

### Stakeholders envolvidos
Hacklab
Secult

### EAP
Apoio à Governança/Engajamento/Documentação Técnica On boarding
