### ISSUE TITLE
Projeto SMAPS

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#398]
### Contexto do épico
Este épico tem o intuito de demandar atividades para apoiar o Projeto SMAPS - ESP para uso da plataforma Mapa da Saúde, através do fornecimento de tutoriais e materiais de apresentação do Mapa.

### Escopo
- [ ] **Revisar Tutorial do Mapa da Saúde**
- [ ] **Converter tutorial Mapa da Saúde para formato Gitbook**
- [ ] **Convidar André (SMAPS) para inception Mapa**

### EAP
Apoio à Governança/Engajamento/Documentação Técnica: Tutoriais
