### ISSUE TITLE
Parceria com Secult

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#399]
### Contexto do épico
Este épico tem o intuito de fortalecer a parceria com a Secretaria de Cultura, no que compete ao projeto Mapa da Saúde, proveniente do Projeto Mapas Culturais, por meio do desenvolvimento de atividades e documentações necessárias.

### Escopo
- [x] #665
- [x] **Definir Pauta de Reunião**
- [ ] **Elaborar Termo de parceria**
- [ ] **Elaborar Plano de Trabalho da parceria**
 - [ ] **Parceria de Treinamento, Documentação e Desenvolvimento**
 - [ ] **Incluir equipe da Secult junto ao contrato com Hacklab**

### Stakeholders envolvidos
Secult

### EAP
Apoio à Governança/Engajamento/Documentação Técnica On boarding
