### ISSUE TITLE
Projeto Vidas Preservadas

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#400]
### Contexto do épico
Este épico tem o intuito de demandar atividades para apoiar o Projeto Vidas Preservadas, de parceria com o Ministério Público, no que compete a utilização da plataforma Mapa da Saúde.

### Escopo
- [x] **Reuniões de entendimento**
- [x] **Oficinas de formação**
- [x] **Inserir taxonomias na lista de Especialidades (Agente) e Tipos de Unidade (Espaços)**

### Stakeholders envolvidos
- Equipe Projeto Vidas Preservadas
- Equipe LINO - Ministério Público

### EAP
Apoio à Governança/Engajamento/Treinamentos: Oficinas para Parceiros
