### ISSUE TITLE
Projeto ForçaSUS

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#401]
### Contexto do épico
Este épico tem o intuito de demandar atividades para apoiar o Projeto de Diagnóstico da Força do Trabalho do SUS - Força SUS, de parceria da ESP/SESA, no que compete a utilização da plataforma Mapa da Saúde.

### Escopo
 - [x] **Reuniões de entendimento**
- [x] **Apoio a elaboração do Projeto**
- [ ] **Cadastro dos Profissionais da Saúde (épico)**
- [ ] **Definição de Taxonomias (categorias, especialidades, etc)**

### Stakeholders envolvidos
Equipe ForçaSUS

### EAP
Apoio à Governança/Institucionalização/Integração do Mapa-ForçaSUS
