### ISSUE TITLE
Gerenciamento de Selos

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/mapadasaude#403]
### Contexto do épico
Este épico tem o intuito de demandar as atividades necessárias ao gerenciamento de selos pela plataforma Mapa da Saúde, pertinentes tanto à gestão como a aplicação dentro da plataforma.

### Escopo
 - [ ] **Criar documentação pertinente aos Selos**
 - [ ] **Definir comissão de avaliação dos Selos**
 - [ ] **Criar política de Distribuição e recompensas**
 - [ ] **Definir as implementações necessárias dentro do sistema para o gerenciamento dos Selos**

### Documento

[Clique aqui](https://docs.google.com/document/d/1hWxIZWQkoxgDi51GnTCrLdY0Nswng025WDni9Ml2mWI/edit?usp=sharing)

### EAP
[Plataforma Interativa/Customização/Gerenciamento de Selos](https://projetos.esp.ce.gov.br/issues/565)
