### ISSUE TITLE
EAP#533 Módulo de homologação - Cuidar Melhor

### ISSUE THREAD

**Issue by Andreqlp** [FeliciLab/mapadasaude#528]
## EAP

[Concurso Município Inovador - Programa Cuidar Melhor\Melhorias na plataforma Mapa da Saúde](https://projetos.esp.ce.gov.br/issues/533)

## **Objetivo**

**Como** gestor de uma oportunidade  
**Quero** selecionar uma modelo de avaliação que permita configurar vários critérios de avaliação para serem validados.
**Para** aceitação de uma inscrição que deve passar para um próxima etapa de avaliação.

**Como** avaliador de uma oportunidade  
**Quero** avaliar as inscrições como de acordo com os critérios do edital
**Para** finalizar minhas avaliações.

## **Contexto**
O edital CONCURSO MUNICÍPIO INOVADOR DO PROGRAMA CUIDAR MELHOR DA SAÚDE NO CEARÁ prevê uma etapa de homologada das inscrições após verificação do cumprimento dos requisitos seguintes requisitos:
- Duração do vídeo de até 3 minutos.
- A prática está de acordo com as temáticas apresentadas no edital. 
- Contar com, no mínimo, 4 (quatro) meses de implantações completadas até a data de início das inscrições.

## **Critérios de Aceitação**

- [ ] tela para a criação de uma oportunidade
**Dado que** sou o gestor e estou criando uma oportunidade  
**Quando** clico no botão de criar oportunidade
**então** posso selecionar a opção "Avaliação de homologação"

![qw.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/58cd3623-3ae7-4ece-b48f-35cc35886702)

- [ ] tela para a configurar a avaliação
**Dado que** sou o gestor e estou configurando os critérios de avaliação
**Quando** clico no botão de adicionar novo critério
**então** posso indicar o titulo do critério que deve ser avaliado e, caso tenha necessidade, indicar o item correspondente no edital.

![qwe.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/6302cd87-0b5c-445f-b391-f0133868ebcd)

- [ ] tela para visualizar as inscrições
**Dado que** sou o avaliador e consultando a lista de projetos que devo avaliar
**Quando** entre na aba avaliações dentro de uma oportunidade
**então** posso visualizar todos os projetos que devo avaliar com a indicação daqueles e avaliei e com qual status ele foi avaliado.

- [ ] tela para realizar a avaliação
**Dado que** sou o avaliador e estou analisando uma inscrição 
**Quando** abro uma inscrição para avaliar
**então** posso visualizar os critérios de avaliação e, para cada item de forma obrigatória, selecionar uma das opções: válido, inválido ou não se aplica. Além disso posso escrever outras informações no campo justificativa / observações. 

![qwer.png](https://images.zenhubusercontent.com/610accbe69320580a6a9c239/ed9f6c9d-562d-42f1-9793-fe2632c2a467)

- [ ] arquivo com a lista das avaliações
**Dado que** sou o gestor e quero baixar o resultado detalhado das avaliações  
**Quando** clico no botão baixar lista de avaliações
**então** posso acessar o resultado detalhado para gerar o resultado ou o parecer da avaliação.

# Observações
Protótipo: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Inscri%C3%A7%C3%B5es?node-id=922%3A566

![image](https://user-images.githubusercontent.com/14170372/140185600-be951dd9-5d71-405e-a0be-ffb0a6cb31f2.png)

![image](https://user-images.githubusercontent.com/14170372/140187212-b02509a8-e762-4d6b-8473-bb88e93e3ae6.png)

![image](https://user-images.githubusercontent.com/14170372/140185632-7bb83cd0-2151-416f-8258-b3587c869fc6.png)

![image](https://user-images.githubusercontent.com/14170372/140185652-25094caa-2963-4b7c-af8e-f76cd0bc75a8.png)

![image](https://user-images.githubusercontent.com/14170372/140188765-8964eede-b4b5-4121-b9e8-6e924f3221f0.png)

**Comment by thaistoscano** [comment]
Acho que é importante vincularmos aos critérios de aceitação a habilitação dos recursos.

**Comment by vicmagpac** [comment]
@thaistoscano caso o preenchimento dos critérios for "NÃO AVALIAR", qual situação deve ser para a avalição?

**Comment by vicmagpac** [comment]
O repositório da implementação do plugin se encontra em https://github.com/EscolaDeSaudePublica/plugin-EvaluationMethodHomolog

**Comment by uira** [comment]
@victorMagalhaesPacheco Que maaaasssaaaaa!!!!
