### ISSUE TITLE
Preparar evento para lançamento oficial do Mapas

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#54]
**Atividades:**

- [x] Criar modelo padrão de Edital (#74 )
- [x] Criar formulário padrão de solicitação de editais (#77 )
- [ ] Realizar treinamento com GTCESP (#75 )
- [ ] Realizar treinamento com os Setores (#75 )
- [ ] Marcar data do lançamento
- [ ] Preparar material de divulgação e lista de convidados
- [ ] Enviar convites, e-mails, mensagens em mídias eletrônicas e redes sociais
- [ ] Preparar inscrições para o evento de lançamento
- [ ] Criar apresentação para o dia do lançamento
- [ ] Apresentação
