### ISSUE TITLE
Documentação padrão: adicionar recepção de arquivos que se repetem em oportunidades

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/mapadasaude#63]
### Objetivo
**Como** participante
**Quando** participa de uma oportunidade ou evento
**Então** precisa reenviar comprovações já solicitadas em outras oportunidades ou eventos

### Escopo
É muito comum, em processos seletivos principalmente, a solicitação de comprovações de diversos documentos, desde documentos de identificação, comprovantes de residência, até certificados de capacitação profissional. 

Para o participante, enviar essa documentação todas as vezes a cada oportunidade ou evento, é desagradável e não agrega valor de usabilidade ao sistema.

Portanto, precisa-se desenvolver um mecanismo onde se recebam essas comprovações, a partir da própria **área do agente**, e um administrador de oportunidade ou evento possa consultar e validar, apenas, para aquele processo.

### Fora de Escopo
Não se aplica

### Critérios de Aceitação
- [ ] Documentos com a definição das regras de aceitação de comprovantes, categorias de comprovantes e prazos de validade
- [ ] Termos de aceite e responsabilidade devidamente disponibilizados ao agente (conforme LGPD)
- [ ] Sessão de submissão de comprovantes disponibilizada para os agentes no painel administrativo pessoal
- [ ] Possibilidade de enviar e/ou excluir seus próprios comprovantes a qualquer tempo
- [ ] Caixa de observações não obrigatória, onde o agente poderá adicionar informações a mais para aquele comprovante submetido
- [ ] Sessão administrativa onde se recebam esses comprovantes 
- [ ] Função de avaliação dos comprovantes emitidos pelos agentes, onde deverão ser aprovados ou reprovados, recebendo um prazo de validade para cada aprovação
- [ ] Alerta ao agente emissor de comprovantes sobre a expiração de sua comprovação, solicitando a emissão de um novo comprovante devidamente atualizado

### Campos da entidade (sugeridos)
- Quem expediu (agente);
- Descrição do pedido de aceitação do comprovante pelo emissor;
- Caminho do documento emitido para download;
- Data e hora da submissão;
- Avaliador (a ser suprimido na visualização do emissor);
- Resposta do avaliador em relação ao comprovante recebido;
- Data e hora da avaliação;
- Situação: aguardando análise, em análise, ativo, não aceito.

### Observações
Entre os documentos mais comuns a serem submetidos, estão: 
- Solicitação do uso do Nome Social;
- Comprovação de exercício da função de jurado;
- Certificados;
- Diplomas;
- Declarações;
- Comprovação como portador de necessidades especiais;
- Comprovantes de endereço.
