### ISSUE TITLE
Roadmap testes migração CNES

### ISSUE THREAD

**Issue by vicmagpac** [FeliciLab/mapadasaude#740]
## Passos para testes

- Testar migração na homologação
   - [x] Inserir novos espaços
   - [x] Atualizar os espaços que foram migrados 
   - [x] Adicionar vínculos ao espaço a um agente

   - [x] Inserir novos agente
   - [x] Atualizar os agentes que foram migrados 
   - [x] Adicionar vínculos ao espaço a um agente

- Ações necessárias para atualização em produção
   - [x] Publicar script python de migração no github
   - [x] Criar ambiente do DW em produção

**Comment by vicmagpac** [comment]
Nos testes realizados foram identificados que os números do CNES dos estabelecimentos de saúde que iniciam com 0 não consta na base.

Número correto: 0445851 - LIFE CLINIC CARIRI
Número na base de dados: 445851

@JesseOliveiraUFC

**Comment by JesseOliveiraUFC** [comment]
Continuando os testes, foi identificado que existem estabelecimentos cujo CNES começa com dois zeros (00) e que estes também não constam corretamente na base de dados. Este é um problema simples de resolver e que na atualização da competência do mês 09 ele será resolvido.

**Comment by vicmagpac** [comment]
Espaços atualizados com sucesso.
![Captura de tela de 2022-10-25 09-30-43.png](https://images.zenhubusercontent.com/60a700715abeb69728eb42ba/59683c9c-ab6c-4c18-95cd-c415860df2f2)

**Comment by vicmagpac** [comment]
Migração dos profissionais em execução na homologação![Captura de tela de 2022-10-25 11-11-17.png](https://images.zenhubusercontent.com/60a700715abeb69728eb42ba/ada8b947-5cce-49d4-a43f-ae41a7be9e99):

**Comment by vicmagpac** [comment]
Finalizada a migração dos agentes na homologação. Total de 140 mil registros atualizados/novos.

![image.png](https://images.zenhubusercontent.com/60a700715abeb69728eb42ba/ef0f74fa-5274-4d11-84c5-83f612c2b659)

**Comment by JesseOliveiraUFC** [comment]
> Nos testes realizados foram identificados que os números do CNES dos estabelecimentos de saúde que iniciam com 0 não consta na base.
> 
> Número correto: 0445851 - LIFE CLINIC CARIRI Número na base de dados: 445851
> 
> @JesseOliveiraUFC

As correções para o problema encontrado foram realizadas com sucesso, além de outras melhorias que foram sugeridas posteriormente:

- [x] Corrigir problemas com estabelecimentos que possuem CNES iniciados com 0 ou 00.
- [x] Corrigir problemas com estabelecimentos que não possuem telefone informado de aparecer somente o DDD.
- [x] Corrigir problema onde aparece somente o código da descrição do serviço fornecido pelo estabelecimento em vez da sua descrição.

**Comment by andersondantas81** [comment]
Foi identificado duplicidade e erros ortográficos nos  tipos de espaços.

![image](https://user-images.githubusercontent.com/4249888/199014929-49b033e0-4e1d-4f97-958b-87b7edd96185.png)

**Comment by andersondantas81** [comment]
![image](https://user-images.githubusercontent.com/4249888/199243033-61234fac-5706-40de-938b-ac65df2097a0.png)

Foi corrigido todas as palavras que estavam sem acentuação em ambiente de produção, tal tarefa foi realizada  manualmente para evitar problemas na migração.

**Comment by vicmagpac** [comment]
Instruções para automatizar a execução do script:

- Iniciar a crontab
`sudo service cron start`

- Adicionar a cron
`crontab -e`

- adicionar o seguinte conteúdo:
`00 23 * * *  docker exec mapadasaude-base_mapasculturais_1 php /var/www/html/protected/application/plugins/CNESIntegration/cron.php`

**Comment by JesseOliveiraUFC** [comment]
Realizada a criação da tabela que armazenará os dados de CPF dos profissionais da saúde. 

![image.png](https://images.zenhubusercontent.com/6231f2fe8cef685d0ca5c6e7/06e2aad6-8d8c-4853-a7ad-9a65959fb2c6)

A atualização dos CPFs será feita pelo @andersondantas81

**Comment by JesseOliveiraUFC** [comment]
Foi inserida uma nova coluna na tabela de relação entre o cpf e o cns dos agente.
Esta nova coluna corrige os cpfs recebidos do webservice que não possuem 11 caracteres.
Esta correção ocorre automaticamente e dinamicamente na tabela, ou seja, se novos dados forem inseridos essa correção já feita automaticamente.

Este problema surge porque os dados provenientes do CNES ignoram os zeros à esquerda.

![image.png](https://images.zenhubusercontent.com/6231f2fe8cef685d0ca5c6e7/969796f8-928e-492c-9d70-3d603459501a)

**Comment by JesseOliveiraUFC** [comment]
Foi inserida uma nova coluna na tabela de relação entre o cpf e o cns dos agente.
Esta nova coluna corrige os cpfs recebidos do webservice que não possuem 11 caracteres.
Esta correção ocorre automaticamente e dinamicamente na tabela, ou seja, se novos dados forem inseridos essa correção já feita automaticamente.

Este problema surge porque os dados provenientes do CNES ignoram os zeros à esquerda.

![image.png](https://images.zenhubusercontent.com/6231f2fe8cef685d0ca5c6e7/969796f8-928e-492c-9d70-3d603459501a)

**Comment by vicmagpac** [comment]
Migração na homologação realizada com sucesso.
Pendente release em produção.

**Comment by vicmagpac** [comment]
Atividade atualizada em produção.

Executar o script 01/12/2022.

**Comment by vicmagpac** [comment]
Processo inicializado na produção. Script executando.

**Comment by andersondantas81** [comment]
Realizado teste no momento da migração para o ambiente de produção:

1.   Criação de um novo usuário no mapa da saúde,
2.   Criação de um novo agente,
3.   Criação de um espaço
4.   No espaço foi testado a adição de administrador e de agentes em um grupo.
5.   Foi testado a edição do dados do Agente e do espaço criado.

**Comment by andersondantas81** [comment]
Cenário: João tem uma Clínica com um médico clínico, João decidiu 
contratar mais um médico clínico e como colaborador do mapa ele atualiza 
os dados da sua clínica(Espaço) no mapa da saúde adicionando esse profissional ao 
grupo de "MEDICO CLINICO" do seu espaço.

De acordo com a regra de negócio implementada hoje no Mapa da Saúde 
todos o vínculos dos estabelecimentos são atualizados de acordo com 
os dados vindos da base de dados do CNES, se alguém inserir um vínculo 
em um espaço(Ex.: Um novo profissional contratado), se na próxima 
atualização esse vínculo não estiver cadastrado na base de dados do CNES 
ele será removido da base de dados do Mapas da Saúde.
@ricardopoppi @nestorufpe

**Comment by vicmagpac** [comment]
Migração finalizada em produção.

**Comment by vicmagpac** [comment]
🎉🎉🎉🎉🎉🎉🎉

**Comment by JesseOliveiraUFC** [comment]
É pra aplaudir de pé e comemorar com um brado do fundo dos pulmões..
